spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=Mohanacsd@08
logging.level.com.cognizant.ormlearn=debug
spring.jpa.hibernate.ddl-auto=validate